### ISSUE TITLE
Cannot find start file of adapter

### ISSUE THREAD

**Issue by Micha2536** [TA2k/ioBroker.velux#2]
Hello ,
the Adapter is not starting.
This ist the Log from iobroker.

host.raspberrypi | 2019-11-21 20:10:21.092 | error | instance system.adapter.velux.0 terminated with code 10 (Cannot find start file of adapter)
-- | -- | -- | --

what can i do to fix the error

**Comment by TA2k** [comment]
remove the instance, remove the adapter and reinstall like described in the forum
https://forum.iobroker.net/topic/26400/test-adapter-velux-v0-0-x

**Comment by Micha2536** [comment]
Thank you, a new installation on the github website was the solution.
