### ISSUE TITLE
velux 0.0.7 Adapter breaks with js-controller:6.0.1

### ISSUE THREAD

**Issue by T-S-Garp** [TA2k/ioBroker.velux#21]
**Describe the bug**  
velux 0.0.7 Adapter breaks with js-controller:6.0.1

**To Reproduce**  
1. Start velux instance v0.0.7 after updating to js-controller 6.0.1

**Expected behavior**  
The instance starts and show green (Connected to host)

**Screenshots & Logfiles**  

host.castor | 2024-06-11 20:50:55.601 | info | Restart adapter system.adapter.velux.0 because enabled
-- | -- | -- | --
host.castor | 2024-06-11 20:50:55.600 | error | instance system.adapter.velux.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: Node.js v18.20.3
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: at node:internal/main/run_main_module:28:49
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1019:12)
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1203:32)
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1364:14)
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.velux/main.js:13:27)
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: TypeError: Class extends value #<Object> is not a constructor or null
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: ^
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: class Velux extends utils.Adapter {
host.castor | 2024-06-11 20:50:55.600 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.velux/main.js:13

**Versions:**  
 - Adapter version: v.0.0.7
 - JS-Controller version: 6.0.1 
 - Node version:  v18.20.3 
 - Operating system: linux (Ubuntu 22.04)

**Additional context**

**Comment by TA2k** [comment]
Please test GitHub version

**Comment by T-S-Garp** [comment]
@TA2k you are the best. The Velux adapter is working again! Many thanks for the lightning-fast repair!!!
![image](https://github.com/TA2k/ioBroker.velux/assets/170171107/9b93567d-bfae-4a4b-ba41-c10fb23ea4ee)
