### ISSUE TITLE
Some review comments

### ISSUE THREAD

**Issue by Apollon77** [TA2k/ioBroker.velux#5]
I had a look at the code and noticed the following:
* https://github.com/TA2k/ioBroker.velux/blob/master/main.js#L100 ... in timeout cases "resp" is empty and so accessing res.statusCode will crash the adapter. You might want to check that resp is defined (not only here, also other places)
* are you 100% sure that https://github.com/TA2k/ioBroker.velux/blob/master/main.js#L105 the interval is not set there already? else you end up in multiple intervals and at least one is not cleanable ... maybe this to check and clear interval before setting new
* in general I persoanlly do not like intervals for external communications (don'z know if I alsready feedbacked that). it is better to use a timeout and set now on end of request - else you can end up in requests piling up because of a network error or such ...

**Comment by TA2k** [comment]
fixed with #22d00b91
